[project]
name = "chess-chase"
version = "1.2.1"
description = "A multiplayer real-time strategy game based on Chess."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kivy",
    "pystun3",
]

[project.optional-dependencies]
build = [
    "pyinstaller",
]
macos-build = [
    "pyinstaller",
]

[tool.uv]
package = false
